### ISSUE TITLE
Prüfschritt 9.1.1.1а translation RU

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/bitv#14]
Bug in Translations in Documentation of Prüfschritt 9.1.1.1а.
URL: https://ilia-brykin.github.io/bitv/steps/9.1.1.1а/
Language: RU
1. Recommended translation: "Смысловое содержание"
![9 1 1 1а](https://github.com/ilia-brykin/bitv/assets/146904622/6a64bcc6-84f4-4200-ac48-9c85926eb495)
2. Recommended translation: "Цель ссылки указана в тексте рядом, **о ней** не нужно догадываться по изображению. На изображение нажимают, потому что **в него**, возможно, легче попасть,
![9 1 1 1а 2](https://github.com/ilia-brykin/bitv/assets/146904622/80666257-800e-4583-9e5e-2ebe50903e71)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Gut
