### ISSUE TITLE
Prüfschritt 9.2.4.7  RU

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/bitv#45]
Bug in Documentation of Prüfschritt 9.2.4.7
URL: https://ilia-brykin.github.io/bitv/steps/9.2.4.7/
Language: RU

There isn't any link

![9 2 4 7](https://github.com/user-attachments/assets/670e13e1-bf40-4a88-abd0-6873f8c3a8dd)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Gut
