### ISSUE TITLE
Prüfschritt 11.7.1 Translation RU, DE

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/bitv#50]
Bug in Translations in Documentation of Prüfschritt 11.7.1
URL: https://ilia-brykin.github.io/bitv/steps/11.7.1/
Language: RU, DE

Tag __TAG_ADDITIONAL_BROWSER_ doesn't translate in both languages.

![11 7 1](https://github.com/user-attachments/assets/5003d9c9-c20e-4f9d-a004-454aa4f2f289)

Recommended translation:

"веб-предложением" 👉 "веб-приложением"

![11 7 1 2](https://github.com/user-attachments/assets/e4fe6d2f-6cd4-4f4e-8628-6bb659039cbe)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Gut
