### ISSUE TITLE
Prüfschritt 12.1.1 Translation RU

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/bitv#51]
Bug in Translations in Documentation of Prüfschritt 12.1.1
URL: https://ilia-brykin.github.io/bitv/steps/12.1.1/
Language: RU

Recommended translation:

"веб-предложение" 👉 "веб-приложение"
"веб-предложения"; "предложения" 👉 "веб-приложения"; "приложения"

![12 1 1](https://github.com/user-attachments/assets/df17c9eb-5adb-4247-ac2a-b723fcb17822)

"предложения" 👉 "приложения"

![12 1 1 2](https://github.com/user-attachments/assets/5fa2d6c7-a469-4efd-a610-a843ca4a46cb)

"веб-предложением" 👉 "веб-приложением"
"предложений" 👉 "приложений"
"предложение" 👉 "приложение"
"предложения" 👉 "приложения"

![12 1 1 3](https://github.com/user-attachments/assets/3443956c-b9bf-43aa-a435-15f93b8081f6)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Gut
