### ISSUE TITLE
Prüfschritt 12.2.2 Translation RU

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/bitv#52]
Bug in Translations in Documentation of Prüfschritt 12.2.2
URL: https://ilia-brykin.github.io/bitv/steps/12.2.2/
Language: RU

I think the information in brackets is duplicated & unwanted.

![12 2 2](https://github.com/user-attachments/assets/3602b0ed-2647-44ff-a257-c76129aaa116)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Gut
